export const ICONS = {
  ANCHOR: "anchor",
  ARROW_DOWN: "arrow-down",
  ARROW_LEFT: "arrow-left",
  ARROW_RIGHT: "arrow-right",
  ARROW_UP: "arrow-up",
  BOMB: "bomb",
  BOOKMARK: "bookmark",
  CHEVRON_DOWN: "chevron-down",
  CHEVRON_LEFT: "chevron-left",
  CHEVRON_RIGHT: "chevron-right",
  CHEVRON_UP: "chevron-up",
  CONTACT: "contact",
  COPY: "copy",
  EXTERNAL_LINK: "external-link",
  FACEBOOK: "facebook",
  GIT_HUB: "git-hub",
  INFO: "info",
  LINKED_IN: "linked-in",
  REACT_JS: "react-js",
  RSS: "rss",
  SAVE: "save",
  SETTINGS: "settings",
  UPWORK: "upwork",
  USER_SEARCH: "user-search",
  X: "x",
} as const;
